### ISSUE TITLE
Design Improvement Suggestion on Pose Publishing

### ISSUE THREAD

**Issue by AndresGalaviz** [NVIDIA-AI-IOT/ros2-nvapriltags#10]
Hello,

I see that the Pose of the detection is published as a TF transform instead of a Pose message. Is there a particular reason this approach was taken?

It seems rather odd to publish it as a TF transform, which is usually reserved for frames of reference. Would it be possible to instead publish the detection as a "Pose" inside the current detection message? That would be more in-line with other ROS perception nodes and make it very simple for it to be "plug and play" with other ROS applications.

**Comment by hemalshahNV** [comment]
Sure! That seems reasonable. It was convenient to have the updates appear in the frame graph but it doesn't have to be.

**Comment by hemalshahNV** [comment]
#13 should resolve this
