### ISSUE TITLE
Remove dependency on apriltag_msgs?

### ISSUE THREAD

**Issue by AndresGalaviz** [NVIDIA-AI-IOT/ros2-nvapriltags#11]
This package is not available for ROS2 Foxy:
nvapriltags_ros2: Cannot locate rosdep definition for [apriltag_msgs]

I can manually install it but this makes listing it as a ROS dependency redundant.

Which can be verified in ROS index:
https://index.ros.org/p/apriltag_msgs/github-christianrauch-apriltag_msgs/#foxy

This package is from a singular developer's personal GitHub and doesn't appear to be actively maintained/developed. Neither does it have a License:
[https://index.ros.org/p/apriltag_msgs/github-christianrauch-apriltag_msgs/](https://index.ros.org/p/apriltag_msgs/github-christianrauch-apriltag_msgs/)

Can this project have its own message definition to reduce this risky dependency? Or perhaps, depend on the message definition from the AprilRobotics package?
https://github.com/AprilRobotics/apriltag_ros/tree/master/apriltag_ros/msg

**Comment by AndresGalaviz** [comment]
Yes, like I mentioned, that one is the one that I can manually install. The issues are the other ones listed in the post.

Also, that package is only released for Dashing.

**Comment by hemalshahNV** [comment]
#13 Resolves, only for Foxy.
