### ISSUE TITLE
XML error

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA-AI-IOT/ros2-nvapriltags#2]
rosdep install --from-paths src --ignore-src
Error(s) in package '/home/agx1/catkin_ws/src/ros2-nvapriltags/package.xml':
The manifest contains invalid XML:
XML or text declaration not at start of entity: line 11, column 0

**Comment by AndreV84** [comment]
@hemalshahNV 
is there a comprehensible instruction 
how to run it [ also install all pre requsites/ dependencies]
on jetson? on x86? on both? on neither of the two?/

**Comment by hemalshahNV** [comment]
I can't promise comprehensible but I'll write up a quick start guide to make it a bit easier to use. Thanks for letting me know. I had kind of stuck with the instructions for the package I was modeling it afterwards and that took some time for me to decipher how to use it too.

You should be able to build the package both Jetson and x86.
________________________________

**Comment by hemalshahNV** [comment]
The copyright header ended up corrupting the package.xml and renaming of the package was not consistent (should all be "nvapriltags_ros2" everywhere). Let me know if you run into any trouble.
